// <auto-generated />
namespace wpf_wakusese.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class script0003 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(script0003));
        
        string IMigrationMetadata.Id
        {
            get { return "201601181513080_script-0003"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
